/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuiasIndexRouteImport } from './routes/guias.index'
import { Route as GuiasSlugRouteImport } from './routes/guias.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiasIndexRoute = GuiasIndexRouteImport.update({
  id: '/guias/',
  path: '/guias/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiasSlugRoute = GuiasSlugRouteImport.update({
  id: '/guias/$slug',
  path: '/guias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guias/$slug': typeof GuiasSlugRoute
  '/guias/': typeof GuiasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guias/$slug': typeof GuiasSlugRoute
  '/guias': typeof GuiasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guias/$slug': typeof GuiasSlugRoute
  '/guias/': typeof GuiasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/guias/$slug' | '/guias/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/guias/$slug' | '/guias'
  id: '__root__' | '/' | '/guias/$slug' | '/guias/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuiasSlugRoute: typeof GuiasSlugRoute
  GuiasIndexRoute: typeof GuiasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guias/': {
      id: '/guias/'
      path: '/guias'
      fullPath: '/guias/'
      preLoaderRoute: typeof GuiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guias/$slug': {
      id: '/guias/$slug'
      path: '/guias/$slug'
      fullPath: '/guias/$slug'
      preLoaderRoute: typeof GuiasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuiasSlugRoute: GuiasSlugRoute,
  GuiasIndexRoute: GuiasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
